version: '3'

services:
  mongo:
    image: mongo
    container_name: mongo2
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/mongo:/data/db
    ports:
        - 27017:27017
  notebook:
    build: .
    ports:
     - "8888:8888"
    command: ["pipenv", "run", "jupyter", "notebook", "--ip=0.0.0.0", "--no-browser", "--allow-root", "--NotebookApp.token=''"]
    volumes:
      - ./:/home/dev/code/

  selenium-hub:
    restart: always
    image: selenium/hub:3.14.0
    container_name: selenium-hub
    ports:
      - "4444:4444"